@extends('layouts/marketing')
@section('content')
    <header class="page-header page-heading">
        <div class="container">
            <h2 class="sub-ttl text-center">Master Service Agreement</h2>
        </div>
    </header><!-- /page-heading -->

    <section class="main">
        <div class="container">
            <div class="row">
                <div class="col-md-10 col-lg-offset-1">

                   
                    <p>This Master Service Agreement (“Agreement”) is entered into as of November 1, 2015 (the “Effective Date”) by and between Code My Views Inc. (“CMV”) and any WordPress Concierge customer (“Client”).</p>


                    <p><strong>1. Services.</strong></p>

                    <div class="row">
                        <div class="col-sm-10 col-sm-offset-1">
                            <p><strong>a. Provision of Services.</strong> Subject to the terms and conditions of this Agreement, including without limitation Client’s payment of all of the fees due hereunder, CMV will provide the services described in each ordering document entered into by the parties (each, an “Order Form”), which may include access to CMV’s proprietary, Internet-accessible technology platform (the “Platform”), Platform support, and other ancillary services (each a “Service” and collectively the “Services”) in accordance with any terms and conditions provided for in such Order Form.  If there is any conflict between the terms of this Agreement and any Order Form, the terms of the Order Form shall control and govern.  Client may use the Services solely for their intended purpose in accordance with this Agreement.</p>

                            <p><strong>b. Infrastructure and Service Availability.</strong>  CMV may host the Services using its own infrastructure or it may engage a third party to host the Services on its behalf, including, but not limited to WP Engine, Heroku, Pagoda Box, and Amazon Web Services.  CMV is not responsible for outages, delays or other issues that arise from a hosting provider’s platform or other issues that arise from third party availability that may affect accessibility, user experience or uptime.</p>

                            <p><strong>c. Support and Maintenance.</strong> CMV will maintain and support the Services during CMV’s standard support hours of 8 am – 6 pm Central Time, Monday- Friday, excluding US Holidays. CMV shall use commercially reasonable efforts to notify Client in advance of any interruption of the Services due to routine (non-emergency) maintenance, and prompt notice of service interruption for non-scheduled maintenance. Support inquiries may be submitted at any time using concierge@codemyviews.com. Support response times are usually within 24 hours.</p>

                            <p><strong>d. Platform License.</strong> During the term of the applicable Order Form, CMV grants Client a non-exclusive, non-transferrable, worldwide, fully paid (upon payment of the amounts due under the applicable Order Form) license to access and use the Platform All rights to the Platform and Services not expressly granted herein or an Order Form are reserved by CMV.</p>
                        </div>
                    </div> 
                    
                    <p><strong>2. Use of the Platform.</strong> Client will access the Platform using username and passwords.  User names and passwords will only be issued to employees of Client or third parties that CMV approves in writing. Client shall immediately notify CMV of any unauthorized disclosure or use of the passwords or access to the Platform or the need to deactivate passwords and provide to CMV its reasonable cooperation to remedy such unauthorized disclosure or use.  Passwords are subject to cancellation or suspension by CMV upon the misuse of passwords by Client. Client shall not (a) copy, reverse engineer, attempt to derive the source code of, or create any derivative works based on the Platform or any aspect thereof, or (b) rent, lease, distribute, transfer, sell, publicly display, publish or otherwise use any portion of the Services or the Platform (including without limitation as a service bureau). In addition, Client shall not remove, alter, or conceal any copyright or other notice, or any mark manifest within the Platform. CMV is hereby granted a royalty-free, fully-paid, worldwide, transferable, sublicenseable, irrevocable and perpetual license to use or incorporate into its products and services any suggestions, enhancements, or other feedback provided by Client relating to the Services or the Platform. Client acknowledges and agrees that, as between Client and CMV, all right, title and interest in and to the Services and/or the Platform (including any microsite, content, and any data that CMV collects or generates in the process of providing the Services or the Platform) and all related intellectual property rights belong exclusively to CMV and its licensors. </p>

                    <p><strong>3. Client Responsibilities and Acknowledgments.</strong> Client shall provide CMV with all information, assistance and materials as reasonably required for CMV to activate and manage the Services for Client pursuant to this Agreement, including without limitation providing CMV with appropriate security credentials and access to any WordPress, provision and maintenance of necessary Domain Name Service (“DNS”) records (if required), and web server reverse proxy configurations (if required). Client shall designate one technical contact as the responsible party for communication with CMV during provision of the Services. Client shall maintain applicable terms of service and/or privacy policies with Client’s end users and web property visitors that unambiguously permits CMV to collect data envisioned by the Services and the Platform.</p>

                    <p><strong>4. Payment.</strong> Client shall pay CMV the fees set forth in each Order Form (“Fees”). Unless otherwise specified in the applicable Order Form, all amounts payable under this Agreement are denominated in U.S. dollars, and Client will pay all such amounts in U.S. dollars. Other than net income taxes imposed on CMV, unless Client provides CMV with a valid tax exemption or a properly completed direct pay certificate, Client will bear all taxes, duties, and other governmental charges resulting from this Agreement. Client shall pay the Fees payable to CMV hereunder within 30 days of receipt of invoices submitted by CMV.  Any unpaid and uncontested balance due and owing shall incur a penalty charge of 1% per month. In addition, if any invoice remains unpaid for more than 30 days, CMV may suspend Client’s access to the Services after giving 10 days’ CMV notice to Client, until CMV has been paid all amounts due. In the event of any dispute with regard to a portion of an invoice, the undisputed portion shall be paid as provided herein, and Client shall notify CMV in writing of the reason for Client’s dispute. Unless provided otherwise on the applicable Order Form, CMV shall be reimbursed by Client for all reasonable expenses incurred by CMV in the performance of the Services, including, but not necessarily limited to, reasonable travel and lodging expenses and communications charges.  At Client’s request, CMV shall submit reimbursement requests, together with back-up receipts, in a form reasonably acceptable to Client.</p>

                    <p><strong>5. Confidential Information.</strong> The term “Confidential Information” in this Agreement means all confidential and proprietary information of a party (“Disclosing Party”) disclosed to the other party (“Receiving Party”), whether orally or in writing, that is designated as confidential or that reasonably should be understood to be confidential given the nature of the information and the circumstances of disclosure. Confidential Information shall not include any information that: (i) is or becomes generally known to the public without breach of any obligation owed to the Disclosing Party; (ii) was known to the Receiving Party prior to its disclosure by the Disclosing Party without breach of any obligation owed to the Disclosing Party; (iii) was independently developed by the Receiving Party without breach of any obligation owed to the Disclosing Party; (iv) is received from a third party without breach of any obligation owed to the Disclosing Party; or (v) is required by law, court order or other legal process to be disclosed. The Receiving Party shall not disclose or use any Confidential Information of the Disclosing Party for any purpose outside the scope of this Agreement, except with the Disclosing Party's prior permission in writing. The Receiving Party will hold all Confidential Information in the strictest confidence and will protect all Confidential Information of the Disclosing Party with not less than the same degree of care that the Receiving Party exercises with respect to its own proprietary and confidential information. If the Receiving Party discloses or uses (or threatens to disclose or use) any Confidential Information of the Disclosing Party in breach of confidentiality protections hereunder, the Disclosing Party shall have the right, in addition to any other remedies available to it, to seek injunctive relief to enjoin such acts, it being specifically acknowledged by the parties that any other available remedies are inadequate</p>

                    <p><strong>6. Disclaimer of Warranties.</strong> EXCEPT AS EXPRESSLY SET FORTH HEREIN, THE SERVICES ARE PROVIDED “AS IS” WITH ALL FAULTS AND WITHOUT REPRESENTATION OR WARRANTY OF ANY KIND, EXPRESS OR IMPLIED. EXCEPT AS EXPRESSLY SET FORTH HEREIN, CMV HEREBY DISCLAIMS ALL REPRESENTATIONS AND WARRANTIES OF ANY KIND, WHETHER EXPRESS, IMPLIED, OR STATUTORY, RELATING TO THIS AGREEMENT, INCLUDING WITHOUT LIMITATION ANY IMPLIED WARRANTIES OF MERCHANTABILITY, ACCURACY, NON-INFRINGEMENT OR FITNESS FOR A PARTICULAR PURPOSE. CMV MAKES NO REPRESENTATION OR WARRANTY CONCERNING THE QUALITY OR TRAFFIC OR LEADS THAT MAY BE GENERATED VIA THE SERVICES.</p>

                    <p><strong>7. Indemnification.</strong></p>

                    <div class="row">
                        <div class="col-sm-10 col-sm-offset-1">
                            <p><strong>a. By CMV.</strong> CMV shall defend Client from and against any and claim, demand, or action in any form brought by a third party against Client, and indemnify and hold Client harmless from any damages, liabilities, losses, costs, and expenses, including reasonable attorneys’ and experts’ fees, in each case that are finally awarded to the third party by a court of competent jurisdiction or otherwise owed in any settlement entered into by Client, in each case to the extent arising from any allegation that the Platform (exclusive of any Client Properties) infringe, misappropriate or otherwise violate any U.S. copyright, patent, trademark, or trade secret.</p>

                            <p><strong>b. By Client.</strong> Client shall defend CMV and its respective officers, directors and employees from and against any claim, demand, or action in any form brought by a third party against CMV, and indemnify and hold CMV harmless from any damages, liabilities, losses, costs, and expenses, including reasonable attorneys’ and experts’ fees, in each case that are finally awarded to the third party by a court of competent jurisdiction or otherwise owed in any settlement entered into by CMV, in each case to the extent arising from (i) Client’s breach of its representations, warranties and obligations under this Agreement; (ii) Client Data, (iii) Client Properties or (iv) configurations, implementations or uses of the Services based on Client’s input, direction, requirements or specifications.</p>
                            
                            <p><strong>c. Exclusions.</strong> Notwithstanding the terms of Subsection 8.a., CMV will have no liability for any infringement claim of any kind to the extent it results from: (a) modification or configuration of the Services made other than by CMV; (b) unauthorized or unlicensed use of the Services; (c) the combination, operation or use of the Services with equipment, devices or software not supplied by CMV to the extent such a claim would have been avoided if the Services were not used in such combination; (d) configurations, implementations or uses of the Services based on Client’s input, direction, requirements or specifications); or (e) third party elements or components of the Services.</p>
                            
                            <p><strong>d.  Procedure.</strong> In each case the indemnified party shall: (i) give the indemnifying party prompt notice of any third-party claim, in writing, to which it is entitled to indemnity under this Section; provided, however, that any delay or failure of such notification will not relieve the indemnifying party of its obligations hereunder except to the extent, if any, that the delay prejudices the indemnifying party; and (ii) reasonably cooperate with the indemnifying party, at the indemnifying party’s expense, in the defense and settlement of such third-party claim. The indemnifying party will, at its option, have sole control of the defense and/or settlement of the third-party claim; provided that, in settling any such third-party claim, the indemnified party shall have the right to participate at its own expense in the defense of such third-party claim through counsel of its own choosing.</p>

                            <p><strong>e.  Rights Upon Infringement.</strong> If Client’s use of the Services hereunder is, or in CMV’s opinion is likely to be, enjoined due to the type of infringement specified in Subsection 8.a. above, CMV may, at its sole option and expense: (a) procure for Client the right to continue using such Services under the terms of this Agreement; (b) replace or modify such Services so that they are non-infringing and substantially equivalent in function; or (c) if options (a) and (b) above cannot be accomplished despite CMV’s reasonable efforts, then CMV may terminate Client’s rights and CMV’s obligations hereunder with respect to the Services and refund any pre-paid fees attributable to any remaining term. The provisions of this Section set forth CMV’s sole and exclusive obligations, and Client’s sole and exclusive remedies, with respect to infringement of any or intellectual property rights of any kind.</p>

                        </div><!--col-->
                    </div><!--row-->

                    <p><strong>8. Term and Termination.</strong> This Agreement is effective as of the Effective Date and will remain in effect so long as any Order Form remains in effect, unless otherwise terminated as provided herein. If the Agreement terminates as a result of there being no active Order Forms, the Agreement will automatically become effective again in the event that a new Order Form is entered into by and between the parties.  Either party may terminate this Agreement or an Order Form if the other party does not cure its material breach of this Agreement or the applicable Order Form within 30 days of receiving CMV notice of the material breach from the non-breaching party. Termination in accordance with this Section 10 will take effect when the breaching party receives CMV notice of termination from the non-breaching party, which notice must not be delivered until the breaching party has failed to cure its material breach during the 30-day cure period. Termination of this Agreement will terminate any then-active Order Forms.</p>

                    <p><strong>9. Effect of Termination.</strong> Termination shall not relieve Client of the obligation to pay any fees or other amounts accrued or payable to CMV prior to the effective date of termination, and CMV may retain all fees paid. Upon termination or expiration of this Agreement each party will destroy all proprietary materials provided by the other party, except any reports or materials prepared specifically for such party by the other party, or if requested by the other party in writing, will return all such materials to the requesting party. Upon termination or expiration of this Agreement or any Order Form (i) Client’s right to access the Services or any portion thereof shall terminate. The provisions of Sections [4 – 14 and 16] survive any termination or expiration of this Agreement.</p>

                    <p><strong>10. Limitation of Liability.</strong> EXCEPT FOR CLAIMS CONCERNING INDEMNIFICATION, CONFIDENTIALITY, AND CMV’S OWNERSHIP OF INTELLECTUAL PROPERTY, IN NO EVENT SHALL EITHER PARTY BE LIABLE TO THE OTHER FOR ANY CONSEQUENTIAL, INCIDENTAL, INDIRECT, EXEMPLARY, PUNITIVE, SPECIAL DAMAGES (INCLUDING LOST PROFITS) OR COSTS OF PROCUREMENT OF SUBSTITUTE SERVICES, EVEN IF SUCH PARTY HAS BEEN PREVIOUSLY ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.  EXCEPT FOR CLAIMS CONCERNING INDEMNIFICATION, CONFIDENTIALITY, AND CMV’S OWNERSHIP OF INTELLECTUAL PROPERTY, IN NO EVENT SHALL EITHER PARTY’S AGGREGATE, CUMULATIVE LIABILITY ARISING OUT OF OR RELATED TO THIS AGREEMENT, WHETHER IN CONTRACT, TORT OR UNDER ANY OTHER THEORY OF LIABILITY, EXCEED THE TOTAL AMOUNT OF FEES PAID BY CLIENT HEREUNDER OR, WITH RESPECT TO ANY SINGLE INCIDENT, THE AMOUNT PAID BY CLIENT HEREUNDER IN THE THREE MONTHS PRECEDING THE INCIDENT. THE FOREGOING SHALL NOT LIMIT CLIENT’S PAYMENT OBLIGATIONS UNDER THIS AGREEMENT.</p>


                    <p><strong>11. Notices.</strong> All notices under this Agreement shall be in writing and shall be deemed given upon delivery with confirmation of receipt.</p>

                    <p><strong>12. Independent Contractors.</strong>  Neither party has any ability to bind the other party to any agreements or other obligations and will not attempt to do so.  This Agreement does not grant any party any right or authority to, and neither party will make any statements, representations, or commitments on behalf of the other party.  CMV and Client are independent contractors, and nothing in this Agreement creates any partnership, joint venture or agency relationship.  As between each other, each party is fully responsible for all persons and entities it employs or retains.</p>

                    <p><strong>13. Force Majeure.</strong> Except for the obligation to pay money, neither party shall be liable for any delays or failures in performance to the extent such delays are caused by labor strikes, war, civil unrest, natural disasters, or other similar circumstances beyond its control.</p>

                    <p><strong>14. Assignment.</strong> Neither party may assign its rights or obligations under this Agreement without the advance CMV consent of the other party, except in the event of a merger or a sale involving all, or substantially all, of a party's stock or assets. Any attempted assignment in violation hereof shall be voidable at the other party's discretion.</p>

                    <p><strong>15. Miscellaneous.</strong> The failure of either party to enforce its rights under this Agreement at any time for any period shall not be construed as a waiver of such rights. No changes or modifications or waivers to this Agreement, an Order Form or the scope of the Services will be effective unless in writing and signed by both parties.  CMV shall have no obligation to commence work in connection with any change until the fee and/or schedule impact of the change is agreed upon by the parties in writing.  CMV and Client shall use good faith efforts to negotiate such changes expeditiously. In the event that any provision of this Agreement shall be determined to be illegal or unenforceable, that provision will be limited or eliminated to the minimum extent necessary so that this Agreement shall otherwise remain in full force and effect and enforceable. This Agreement (along with any Order Forms) constitutes the entire, complete and final understanding and agreement by and between the parties with respect to the subject matter of this Agreement, and supersedes any prior oral or CMV agreements with respect to the subject of this Agreement. This Agreement shall be governed by and construed in accordance with the laws of the State of Texas without regard to the conflicts of laws provisions thereof. Jurisdiction and venue for all disputes hereunder is limited to the state and federal courts located within Travis County, Texas and the parties hereby consent to and waive any objections with respect to such jurisdiction and venue. This Agreement may be signed in counterparts, including by facsimile or electronic copy, each of which will be deemed an original, and all such counterparts together constituting one and the same Agreement.</p>
                </div>
            </div>
        </div><!--container-->
    </section>


    @include('partials/contact-info')
@endsection