{
    "related_to_brief": [], {{-- array of ids, briefs can be related to other briefs.  For example, a front end brief can have a WordPress brief associated with it --}}
    "summary": "", {{-- Here is a quick summary about the project. This project summary will never have more than 300 characters and should serve as a brief overview of the project. --}}
    "layout_type": "",  {{-- blanks.select.layout_type --}}
    "global": {
        "notes": "", {{-- This will be a block of HTML generated by a WYSIWYG --}}
        "checklist": [
          {{-- blanks.checklist_item --}}
        ]
    },
    "views": [
        {{-- blanks.views_item --}}
    ],
    "modals": [
        {{-- blanks.modal_item --}}
    ]
}